-- H2 2.1.214;
;             
CREATE USER IF NOT EXISTS "SA" SALT 'da73d14137da6eec' HASH 'bf18b5046a384762f18914bdeb02bb287b3a83431ea76e8ed697eeb3f1d09fee' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."EMPLOYEE"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 22) NOT NULL,
    "SALARY" FLOAT(53),
    "EMAIL" CHARACTER VARYING(255),
    "FIRST_NAME" CHARACTER VARYING(255),
    "GRADE" CHARACTER VARYING(255),
    "LAST_NAME" CHARACTER VARYING(255)
);  
ALTER TABLE "PUBLIC"."EMPLOYEE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");     
-- 21 +/- SELECT COUNT(*) FROM PUBLIC.EMPLOYEE;               
INSERT INTO "PUBLIC"."EMPLOYEE" VALUES
(1, 5000.0, 'aarav.sharma@example.com', 'Aarav', 'A', 'Sharma'),
(2, 6000.0, 'ishaan.patel@example.com', 'Ishaan', 'B', 'Patel'),
(3, 4500.0, 'kiara.kumar@example.com', 'Kiara', 'A', 'Kumar'),
(4, 7000.0, 'arjun.singh@example.com', 'Arjun', 'A', 'Singh'),
(5, 4500.0, 'kiara.kumar@example.com', 'Kiara', 'A', 'Kumar'),
(6, 5000.0, 'yash.sharma@example.com', 'Yash', 'A', 'Sharma'),
(7, 5500.0, 'riya.gupta@example.com', 'Riya', 'B', 'Gupta'),
(8, 6500.0, 'aryan.verma@example.com', 'Aryan', 'B', 'Verma'),
(9, 4800.0, 'sara.khan@example.com', 'Sara', 'C', 'Khan'),
(10, 5500.0, 'rahul.shah@example.com', 'Rahul', 'B', 'Shah'),
(11, 5200.0, 'mohit.gupta@example.com', 'Mohit', 'C', 'Gupta'),
(12, 7500.0, 'raj.malhotra@example.com', 'Raj', 'A', 'Malhotra'),
(13, 4800.0, 'neha.sharma@example.com', 'Neha', 'C', 'Sharma'),
(14, 6200.0, 'kabir.kapoor@example.com', 'Kabir', 'B', 'Kapoor'),
(15, 5100.0, 'ruhi.singh@example.com', 'Ruhi', 'C', 'Singh'),
(16, 5100.0, 'ruhi.singh@example.com', 'Ruhi', 'C', 'Singh'),
(17, 6800.0, 'amit.kumar@example.com', 'Amit', 'B', 'Kumar'),
(18, 4900.0, 'sneha.verma@example.com', 'Sneha', 'C', 'Verma'),
(19, 7300.0, 'rajat.singh@example.com', 'Rajat', 'A', 'Singh'),
(20, 5500.0, 'anika.gupta@example.com', 'Anika', 'B', 'Gupta'),
(21, 6000.0, 'vikram.shah@example.com', 'Vikram', 'B', 'Shah');  
