-- H2 2.1.214;
;
CREATE USER IF NOT EXISTS "SA" SALT '44559d15b0c12532' HASH '8c8c030f803f2fc521c6a1ee87fb8d0d1e8ac540c6d0733ec7c4abb66dad960d' ADMIN;
CREATE MEMORY TABLE "PUBLIC"."DEPARTMENT"
(
    "ID"   INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 RESTART WITH 6) NOT NULL,
    "CODE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);
ALTER TABLE "PUBLIC"."DEPARTMENT"
    ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY ("ID");
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.DEPARTMENT;              
INSERT INTO "PUBLIC"."DEPARTMENT"
VALUES (1, '5A', 'Engineering'),
       (2, '5A', 'Manufacturing'),
       (3, '4A', 'T-Mobile'),
       (4, '2A', 'T-Rex'),
       (5, 'GA', 'JIB');
CREATE MEMORY TABLE "PUBLIC"."EMPLOYEE"
(
    "ID"                   INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 RESTART WITH 24) NOT NULL,
    "SALARY"               FLOAT(53),
    "EMAIL"                CHARACTER VARYING(255),
    "FIRST_NAME"           CHARACTER VARYING(255),
    "GRADE"                CHARACTER VARYING(255),
    "LAST_NAME"            CHARACTER VARYING(255),
    "MAPPED_TO_DEPARTMENT" INTEGER
);
ALTER TABLE "PUBLIC"."EMPLOYEE"
    ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY ("ID");
-- 23 +/- SELECT COUNT(*) FROM PUBLIC.EMPLOYEE;               
INSERT INTO "PUBLIC"."EMPLOYEE"
VALUES (1, 5000.0, 'aarav.sharma@example.com', 'Aarav', 'A', 'Sharma', NULL),
       (2, 6000.0, 'ishaan.patel@example.com', 'Ishaan', 'B', 'Patel', NULL),
       (3, 4500.0, 'kiara.kumar@example.com', 'Kiara', 'A', 'Kumar', NULL),
       (4, 7000.0, 'arjun.singh@example.com', 'Arjun', 'A', 'Singh', NULL),
       (5, 4500.0, 'kiara.kumar@example.com', 'Kiara', 'A', 'Kumar', NULL),
       (6, 5000.0, 'yash.sharma@example.com', 'Yash', 'A', 'Sharma', NULL),
       (7, 5500.0, 'riya.gupta@example.com', 'Riya', 'B', 'Gupta', NULL),
       (8, 6500.0, 'aryan.verma@example.com', 'Aryan', 'B', 'Verma', NULL),
       (9, 4800.0, 'sara.khan@example.com', 'Sara', 'C', 'Khan', NULL),
       (10, 5500.0, 'rahul.shah@example.com', 'Rahul', 'B', 'Shah', NULL),
       (11, 5200.0, 'mohit.gupta@example.com', 'Mohit', 'C', 'Gupta', NULL),
       (12, 7500.0, 'raj.malhotra@example.com', 'Raj', 'A', 'Malhotra', NULL),
       (13, 4800.0, 'neha.sharma@example.com', 'Neha', 'C', 'Sharma', NULL),
       (14, 6200.0, 'kabir.kapoor@example.com', 'Kabir', 'B', 'Kapoor', NULL),
       (15, 5100.0, 'ruhi.singh@example.com', 'Ruhi', 'C', 'Singh', NULL),
       (16, 5100.0, 'ruhi.singh@example.com', 'Ruhi', 'C', 'Singh', NULL),
       (17, 6800.0, 'amit.kumar@example.com', 'Amit', 'B', 'Kumar', NULL),
       (18, 4900.0, 'sneha.verma@example.com', 'Sneha', 'C', 'Verma', NULL),
       (19, 7300.0, 'rajat.singh@example.com', 'Rajat', 'A', 'Singh', NULL),
       (20, 5500.0, 'anika.gupta@example.com', 'Anika', 'B', 'Gupta', NULL),
       (21, 6000.0, 'vikram.shah@example.com', 'Vikram', 'B', 'Shah', NULL),
       (22, 99000.0, 'devendra@gmail.com', 'Devendra', '6A', 'Sanghavi', 1),
       (23, 99.0, 'moko@gmail.com', 'Ko', '6A', 'MO', 3);
ALTER TABLE "PUBLIC"."EMPLOYEE"
    ADD CONSTRAINT "PUBLIC"."FK4KM0JS2SX0WYRRW6GPG7ULWXI" FOREIGN KEY ("MAPPED_TO_DEPARTMENT") REFERENCES "PUBLIC"."DEPARTMENT" ("ID") NOCHECK;
